version: '3'

networks:
  retwis:

services:
  nginx-server2:
    image: nginx:stable-alpine
    container_name: nginx-server2
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-build
      - redis
    networks:
      - retwis

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - retwis

  php-build:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-build
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - retwis
volumes:
    db_data: {}